### ISSUE TITLE
Calling the create function on the OrganizationFactory is not working

### ISSUE THREAD

**Issue by lserafin** [windingtree/debugging-tools#5]
Hi, 

I am trying to register an ORG.ID via the WT Debugger Interface (calling the create function on the OrganizationFactory contract) on the Ropsten Network.

This is the ORG.ID that I would like to register: https://gist.github.com/lserafin/c04935e3416bd2aef674390279e833a9

This is the hash:
0x5b0348d21a0714ff4b1ade330b4f716718418c9c3900bdd4f8152f3fda0a0415

After I accepted the transaction on the MetaMask interface the transaction is failing: https://ropsten.etherscan.io/tx/0xd75bacbaf37dc072e56aa53a0cbf4378c07d940b98615a3ed8fb5504e3fb48f4

I am not sure if this is related to the WT Debugger or if I am doing something wrong here ? 

Thanks & Regards,
Luzian

**Comment by JirkaChadima** [comment]
Hi, the problem is probably the following:

You are running the transaction against the Entrypoint address (0xa268937c2573e2AB274BF6d96e88FfE0827F0D4D), but are trying to call the methods on the Factory (which is on 0x8E6463ea056d812094Ed514455Ab3C88fc23D59C).

The debugger seems to not reflect the contract type change in the address field. Although I'm not sure if its supposed to.

The solution is probably to fill in the proper address, switch the contract type to OrganizationFactory and then it should work.

**Comment by lserafin** [comment]
@JirkaChadima : Thank you very much!
